---
google:
  serviceAccountKeyFile: 'config/service_account_key.json'
  subject: '...@gmail.com'

roomBulbLabelOverrides: {
  roomOne: '...bulb.id'
}

timing:
  meetingEndIntervalMinutes: 2
  meetingWarningIntervalMinutes: 5

lifx:
  token: '...'
