---
google:
  serviceAccountKeyFile: 'config/service_account_key.json'
  subject: '...@gmail.com'

lifx:
  token: '...'

roomBulbLabelOverrides: {
  roomOne: '...bulb.id'
}

meetingIntervalMin:
  start: 3
  warn: 5
  end: 2

pulse:
  onStart: true
  onEnd: true

log:
  level: warn
