---
google:
  timezone: 'UTC+00:00'
  serviceAccountKeyFile: 'config/service_account_key.json'
  subject: '...@gmail.com'

roomBulbLabelOverrides: {
  roomOne: '...@resource.calendar.google.com'
}

timing:
  meetingEndIntervalMinutes: 3
  meetingWarningIntervalMinutes: 5
